version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src/:/app/src/
    ports:
      - "3000:5173"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - "8080:3000"
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    volumes: 
      - ./database/schema.ddl.sql:/docker-entrypoint-initdb.d/init.ddl.sql
    environment:
      POSTGRES_DB: hunters
      POSTGRES_USER: hunters
      POSTGRES_PASSWORD: super
    ports:
      - "5434:5432"
